from __future__ import annotations
from dataclasses import dataclass, field
from typing import ClassVar, Dict, List, Optional, TypeAlias

from progression_problems.constants import CM_PER_INCH
from progression_problems.TRIGA.fuel_element import FuelElement
from progression_problems.TRIGA.graphite_element import GraphiteElement
from progression_problems.TRIGA.NETL.central_thimble import CentralThimble
from progression_problems.TRIGA.NETL.fuel_follower_control_rod import FuelFollowerControlRod
from progression_problems.TRIGA.NETL.source_holder import SourceHolder
from progression_problems.TRIGA.NETL.transient_rod import TransientRod


@dataclass
class Core:
    """ Dataclass for the TRIGA core.

    Default control rod positions are arbitrarily set to
    0 steps (Fully inserted).  The following core locations
    are reserved for non-fuel elements (Ref [1]_ Figure 4.4 & pg 4-9):
    - Transient Rod:   C-01
    - Regulating Rod:  C-07
    - Shim 1 Rod:      D-06
    - Shim 2 Rod:      D-14
    - Central Thimble: A-01

    Attributes
    ----------
    pitch : float
        Hexagonal lattice pitch [cm].
        Default:  1.714 * CM_PER_INCH (Ref. [2]_ pg 54)
    central_thimble : CentralThimble
        The TRIGA central thimble specifications.
        Default: CentralThimble()
    transient_rod : TransientRod
        The TRIGA transient rod specifications.
        Default: TransientRod()
    regulating_rod : FuelFollowerControlRod
        The TRIGA regulating rod specifications.
        Default: FuelFollowerControlRod()
    shim_1_rod : FuelFollowerControlRod
        The TRIGA shim 1 rod specifications.
        Default: FuelFollowerControlRod()
    shim_2_rod : FuelFollowerControlRod
        The TRIGA shim 2 rod specifications.
        Default: FuelFollowerControlRod()
    core_loading : Dict[str, Optional[Loadable]]
        Map of mutable core locations and their contents.  Keys must be in RING_MAP and not in
        the locations reserved for the control rods, central thimble, or water holes
        (i.e. 'A-01', 'C-01', 'C-07', 'D-06', 'D-14', 'G-01', 'G-07', 'G-13', 'G-19', 'G-25', 'G-31').
        Keys in RING_MAP that are not specified in core_loading will take the value of the missing keys
        in the dictionary generated by Core.default_loading.
    core_map : Dict[str, Optional[Element]]
        Map of core locations and their contents.  Keys are all locations in RING_MAP.

    RING_MAP : ClassVar[List[List[str]]]
        List of lists representing the TRIGA core ring map. Each inner list represents a ring in the core.  Rings are
        ordered from outermost ring (first list) to innermost ring (last list). Ref. [1]_ Figure 1.2

    References
    ----------
    .. [1] "University of Texas at Austin Nuclear Engineering Teaching Laboratory
           TRIGA Research Reactor", August 2023,
           https://www.nrc.gov/docs/ML2327/ML23279A146.pdf

    .. [2] D. R. Redhouse, et al., "Radiation Characterization Summary: NETL Beam Port
           1/5 Free-Field Environment at the 128-inch Core Centerline Adjacent Location,
           (NETL-FF-BP1/5-128-cca).", Nov. 2022. https://doi.org/10.2172/1898256
    """

    RING_MAP: ClassVar[List[List[str]]] = [
        ["G-01", "G-02", "G-03", "G-04", "G-05", "G-06",
         "G-07", "G-08", "G-09", "G-10", "G-11", "G-12",
         "G-13", "G-14", "G-15", "G-16", "G-17", "G-18",
         "G-19", "G-20", "G-21", "G-22", "G-23", "G-24",
         "G-25", "G-26", "G-27", "G-28", "G-29", "G-30",
         "G-31", "G-32", "G-33", "G-34", "G-35", "G-36"],
        ["F-01", "F-02", "F-03", "F-04", "F-05", "F-06",
         "F-07", "F-08", "F-09", "F-10", "F-11", "F-12",
         "F-13", "F-14", "F-15", "F-16", "F-17", "F-18",
         "F-19", "F-20", "F-21", "F-22", "F-23", "F-24",
         "F-25", "F-26", "F-27", "F-28", "F-29", "F-30"],
        ["E-01", "E-02", "E-03", "E-04", "E-05", "E-06",
         "E-07", "E-08", "E-09", "E-10", "E-11", "E-12",
         "E-13", "E-14", "E-15", "E-16", "E-17", "E-18",
         "E-19", "E-20", "E-21", "E-22", "E-23", "E-24"],
        ["D-01", "D-02", "D-03", "D-04", "D-05", "D-06",
         "D-07", "D-08", "D-09", "D-10", "D-11", "D-12",
         "D-13", "D-14", "D-15", "D-16", "D-17", "D-18"],
        ["C-01", "C-02", "C-03", "C-04", "C-05", "C-06",
         "C-07", "C-08", "C-09", "C-10", "C-11", "C-12"],
        ["B-01", "B-02", "B-03", "B-04", "B-05", "B-06"],
        ["A-01"]]

    # Type aliases for core elements
    Loadable: TypeAlias = FuelElement | GraphiteElement | SourceHolder
    Fixture: TypeAlias = CentralThimble | TransientRod | FuelFollowerControlRod
    Element: TypeAlias = FuelElement | GraphiteElement | SourceHolder | CentralThimble | TransientRod | FuelFollowerControlRod

    pitch: float = 1.714 * CM_PER_INCH
    central_thimble: CentralThimble = field(default_factory=CentralThimble)
    core_loading: Dict[str, Optional[Loadable]] = field(default_factory=lambda: Core.default_loading())  # pylint: disable=unnecessary-lambda
    transient_rod: TransientRod = field(default_factory=TransientRod)
    regulating_rod: FuelFollowerControlRod = field(default_factory=FuelFollowerControlRod)
    shim_1_rod: FuelFollowerControlRod = field(default_factory=FuelFollowerControlRod)
    shim_2_rod: FuelFollowerControlRod = field(default_factory=FuelFollowerControlRod)
    core_map: Dict[str, Optional[Element]] = field(default_factory=dict)

    def __post_init__(self):
        for location in self.core_loading:
            assert any(location in ring for ring in Core.RING_MAP), \
                f"Invalid core location '{location}' in core_loading."
            assert location not in ["A-01", "C-01", "C-07", "D-06", "D-14",
                                    "G-01", "G-07", "G-13", "G-19", "G-25", "G-31"], \
                f"Core location '{location}' is reserved for control rods or central thimble."

        self.core_map = {
            "A-01": self.central_thimble,
            "C-01": self.transient_rod,
            "C-07": self.regulating_rod,
            "D-06": self.shim_1_rod,
            "D-14": self.shim_2_rod,
            "G-01": None,
            "G-07": None,
            "G-13": None,
            "G-19": None,
            "G-25": None,
            "G-31": None}

        default_loading = Core.default_loading()
        for ring in Core.RING_MAP:
            for location in ring:
                self.core_map[location] = self.core_loading.get(location, default_loading.get(location, None))

    @classmethod
    def default_loading(cls) -> Dict[str, Optional[Loadable]]:
        """Generates an arbitrary default core loading map.

        This is similar though not entirely identical to the
        loading map presented in Ref. [2]_ pg. 48-49

        Returns
        -------
        Dict[str, Optional[Loadable]]
            A copy of the default core loading map.
        """
        return {
            "B-01": FuelElement(), "B-02": FuelElement(), "B-03": FuelElement(),
            "B-04": FuelElement(), "B-05": FuelElement(), "B-06": FuelElement(),
            "C-02": FuelElement(), "C-03": FuelElement(),
            "C-04": FuelElement(), "C-05": FuelElement(), "C-06": FuelElement(),
            "C-08": FuelElement(), "C-09": FuelElement(),
            "C-10": FuelElement(), "C-11": FuelElement(), "C-12": FuelElement(),
            "D-01": FuelElement(), "D-02": FuelElement(), "D-03": GraphiteElement(),
            "D-04": FuelElement(), "D-05": FuelElement(),
            "D-07": FuelElement(), "D-08": FuelElement(), "D-09": FuelElement(),
            "D-10": FuelElement(), "D-11": FuelElement(), "D-12": FuelElement(),
            "D-13": FuelElement(), "D-15": FuelElement(),
            "D-16": FuelElement(), "D-17": FuelElement(), "D-18": FuelElement(),
            "E-01": FuelElement(), "E-02": FuelElement(), "E-03": FuelElement(),
            "E-04": FuelElement(), "E-05": FuelElement(), "E-06": FuelElement(),
            "E-07": FuelElement(), "E-08": FuelElement(), "E-09": FuelElement(),
            "E-10": FuelElement(), "E-11": None,          "E-12": FuelElement(),
            "E-13": FuelElement(), "E-14": FuelElement(), "E-15": FuelElement(),
            "E-16": FuelElement(), "E-17": FuelElement(), "E-18": FuelElement(),
            "E-19": FuelElement(), "E-20": FuelElement(), "E-21": FuelElement(),
            "E-22": FuelElement(), "E-23": FuelElement(), "E-24": FuelElement(),
            "F-01": FuelElement(), "F-02": FuelElement(), "F-03": FuelElement(),
            "F-04": FuelElement(), "F-05": FuelElement(), "F-06": FuelElement(),
            "F-07": FuelElement(), "F-08": FuelElement(), "F-09": FuelElement(),
            "F-10": FuelElement(), "F-11": FuelElement(), "F-12": FuelElement(),
            "F-13": None,          "F-14": None,          "F-15": FuelElement(),
            "F-16": FuelElement(), "F-17": FuelElement(), "F-18": FuelElement(),
            "F-19": FuelElement(), "F-20": FuelElement(), "F-21": FuelElement(),
            "F-22": FuelElement(), "F-23": FuelElement(), "F-24": FuelElement(),
            "F-25": FuelElement(), "F-26": FuelElement(), "F-27": FuelElement(),
            "F-28": FuelElement(), "F-29": FuelElement(), "F-30": FuelElement(),
            "G-02": FuelElement(), "G-03": FuelElement(),
            "G-04": FuelElement(), "G-05": FuelElement(), "G-06": FuelElement(),
            "G-08": FuelElement(), "G-09": FuelElement(),
            "G-10": FuelElement(), "G-11": FuelElement(), "G-12": FuelElement(),
            "G-14": FuelElement(), "G-15": FuelElement(),
            "G-16": FuelElement(), "G-17": FuelElement(), "G-18": FuelElement(),
            "G-20": FuelElement(), "G-21": FuelElement(),
            "G-22": FuelElement(), "G-23": FuelElement(), "G-24": FuelElement(),
            "G-26": FuelElement(), "G-27": FuelElement(),
            "G-28": FuelElement(), "G-29": FuelElement(), "G-30": FuelElement(),
            "G-32": SourceHolder(),"G-33": FuelElement(),
            "G-34": None,          "G-35": FuelElement(), "G-36": FuelElement()}
